apiVersion: v1
kind: Service
metadata:
    name: k8s-tp-nginx-service
spec:
    selector:
        app: k8s-tp
    ports:
        -   protocol: TCP
            port: 80
            targetPort: 80
    type: NodePort
